sudo:  required
services:
  - docker

before_install:
  - docker build -t carlosalonso/docker-react-revisited -f Dockerfile.dev .

script:
  - docker run -e CI=true carlosalonso/docker-react-revisited npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-revisited"
  env: "Dockerreactrevisited-env"
  bucket_name: "elasticbeanstalk-eu-central-1-784097295211"
  bucket_path: "docker-react-revisited"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
