sudo:  required
services:
  - docker

before_install:
  - docker build -t carlosalonso/docker-react-revisited -f Dockerfile.dev .

script:
  - docker run -e CI=true carlosalonso/docker-react-revisited npm run test
  